name: Build and Deploy
on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm ci

          npm run build --workspace=@natewilcox/zelda-battle-shared
          npm run build --workspace=@natewilcox/zelda-battle-client
          npm run build --workspace=@natewilcox/zelda-battle-server

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            packages/shared/dist
            packages/client/dist
            packages/server/build
          retention-days: 1
          
  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - run: npm publish --workspace=@natewilcox/zelda-battle-server --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

# jobs:
#   npm-build:
#     uses: natewilcox/actions-workflows/.github/workflows/npm-publish.yml@main
#     secrets:
#       NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

#   aws-publish:
#     needs: npm-build
#     uses: natewilcox/actions-workflows/.github/workflows/aws-s3-publish.yml@main
#     secrets:
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
#     with:
#       AWS_REGION: 'us-east-2'
#       S3_BUCKET_NAME: 'zelda.natewilcox.io'