name: Build and Deploy
on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm ci

          npm run build --workspace=@natewilcox/zelda-battle-shared
          npm run build --workspace=@natewilcox/zelda-battle-client
          npm run build --workspace=@natewilcox/zelda-battle-server

      - name: Archive library build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'build-artifacts-library'
          path: |
            ./packages/shared/dist/
          retention-days: 1

      - name: Archive client build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'build-artifacts-client'
          path: |
            ./packages/client/dist/
          retention-days: 1

      - name: Archive server build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'build-artifacts-server'
          path: |
            ./packages/server/build/
          retention-days: 1
          
  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: 'build-artifacts-server'
          path: packages/server/build/
      - run: |
          ls packages/server/build/ -ltr
      #     # npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - name: Patch version
      #   # if: github.event_name == 'release'
      #   run: |
      #     git config --local user.email "natewilcox@gmail.com"
      #     git config --local user.name "GitHub Action"

      #     npm version patch --workspace=@natewilcox/zelda-battle-server -m "Automated version bump [skip ci]"
      #     git push

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Download build artifact
  #     uses: actions/download-artifact@v4
  #     with:
  #       name: 'build-artifacts'

  #   - name: Set up AWS credentials
  #     uses: aws-actions/configure-aws-credentials@v1
  #     with:
  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       aws-region: us-east-2

  #   - name: Copy files to the S3 bucket
  #     run: |
  #       aws s3 sync ./client/dist s3://zelda-battle.natewilcox.io --acl=private --delete

  #   - name: Invalidate CloudFront cache
  #     run: |
  #       aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/index.html"