name: Build and Deploy
on: [push, pull_request]

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: |
          npm ci
          npm run --build --workspace=@natewilcox/zelda-battle-client


# jobs:
#   npm-build:
#     uses: natewilcox/actions-workflows/.github/workflows/npm-publish.yml@main
#     secrets:
#       NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

#   aws-publish:
#     needs: npm-build
#     uses: natewilcox/actions-workflows/.github/workflows/aws-s3-publish.yml@main
#     secrets:
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
#     with:
#       AWS_REGION: 'us-east-2'
#       S3_BUCKET_NAME: 'zelda.natewilcox.io'